spring.application.name=ok
server.port=8000

spring.datasource.url=jdbc:postgresql://localhost:5432/db_rutas
spring.datasource.username=admin
spring.datasource.password=admin
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.jackson.serialization.indent_output=true

spring.threads.virtual.enabled=true